source: src
destination: docs
include: [src/.nojekyll]
exclude: [priv/, FumoNet*]
plugins: [jekyll-paginate-v2]

url: https://driftini.github.io
baseurl: "/driftini.github.io"

permalink: /:categories/:year/:month/:day/:title

collections:
  posts:
    permalink: /blog/:name

  artwork:
    output: true

  wallpapers:
    output: true

  dailies:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_posts"
    values:
      layout: postDetail
      blogPost: true
  -
    scope:
      path: "_drafts"
    values:
      layout: postDetail
      blogPost: true
  -
    scope:
      path: "_artwork"
    values:
      layout: postDetail
  -
    scope:
      path: "_wallpapers"
    values:
      layout: postDetail
  -
    scope:
      path: "_dailies"
    values:
      layout: doodleMonth

pagination:
  enabled: true
  per_page: 10
  title: ":title - Page :num"
  sort_reverse: true
  trail:
    before: 3
    after: 3
